import { PrebuiltVoice, VoiceStylePreset, SampleScript } from '../types';

export const PREBUILT_VOICES: PrebuiltVoice[] = [
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'Feminine',
    timbreDescription: 'Warm, melodic, and soothing with smooth chest resonance and gentle articulation.',
    timbreDescriptionZh: '温和悦耳、轻柔如水，带有抚慰人心的胸腔共鸣与圆润清晰的咬字。',
    bestFor: 'Audiobooks, guided meditation, documentaries, and empathetic assistants',
    bestForZh: '有声书故事、正念冥想、情感电台、纪录片解说及温和亲切的助理',
    tone: ['Warm', 'Soothing', 'Melodic', 'Empathetic'],
    toneZh: ['温暖舒缓', '圆润悦耳', '柔和亲切', '治愈治愈'],
    pitchGuide: 'Mezzo-Soprano / Mid-High register',
    pitchGuideZh: '女中音 / 中高音区',
    recommendedLanguages: ['zh', 'en'],
    suitabilityTagZh: '⭐ 中英双语兼优 (特别推荐中文)',
    suitabilityTagEn: '⭐ Bilingual Pro (Excels at Chinese & English)',
    suitabilityDescriptionZh: '中文普通话发音极其温润自然，四声调值过渡平滑，读中文和英文故事都极具感染力。',
    suitabilityDescriptionEn: 'Exquisite tonal fluidity for Mandarin Chinese while retaining gentle, melodic clarity in English.',
  },
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'Neutral',
    timbreDescription: 'Clear, balanced, articulate, and modern with neutral intonation and pristine diction.',
    timbreDescriptionZh: '清澈平衡、发音极标准清晰，现代感强，声线兼顾知性与专业度。',
    bestFor: 'Professional narration, technical documentation, navigation, and e-learning',
    bestForZh: '专业课件讲解、科技发布、新闻简报、多语言导航与知识分享',
    tone: ['Articulate', 'Crisp', 'Balanced', 'Modern'],
    toneZh: ['吐字清晰', '清脆现代', '平衡中正', '专业知性'],
    pitchGuide: 'Alto-Tenor / Balanced register',
    pitchGuideZh: '女低音至男高音 / 平衡音区',
    recommendedLanguages: ['zh', 'en'],
    suitabilityTagZh: '⭐ 中英双语兼优 (多语言标准发音)',
    suitabilityTagEn: '⭐ Bilingual Pro (Pristine Diction)',
    suitabilityDescriptionZh: '发音辨识度高，无论是科技词汇还是中文长难句，字正腔圆，非常适合中英文双语播报。',
    suitabilityDescriptionEn: 'Exceptionally articulate consonants and neutral intonation, ideal for tech explainers and bilingual delivery.',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'Masculine',
    timbreDescription: 'Deep, commanding baritone with robust low-end presence and steady confidence.',
    timbreDescriptionZh: '沉稳雄厚、充满磁性的低沉男声，具备强烈的戏剧张力与稳健魄力。',
    bestFor: 'Cinematic trailers, executive announcements, news anchors, and epic audiobooks',
    bestForZh: '电影预告片、庄重大气的品牌发布、正史历史纪录片与史诗奇幻独白',
    tone: ['Authoritative', 'Deep', 'Commanding', 'Resonant'],
    toneZh: ['沉稳权威', '磁性浑厚', '大气磅礴', '共鸣深沉'],
    pitchGuide: 'Baritone / 110-130 Hz',
    pitchGuideZh: '低男中音 / 110-130 Hz',
    recommendedLanguages: ['zh', 'en'],
    suitabilityTagZh: '🎙️ 沉稳大气 (适合中英文庄重叙事)',
    suitabilityTagEn: '🎙️ Deep Baritone (Epic English & Chinese)',
    suitabilityDescriptionZh: '浑厚底音强劲，读英语如好莱坞电影大片，读中文如历史正剧旁白，厚重大气。',
    suitabilityDescriptionEn: 'Resonant low-end power suited for cinematic trailers, executive speeches, and epic storytelling in both languages.',
  },
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'Masculine',
    timbreDescription: 'Energetic, crisp, and dynamic with youthful vibrance and expressive cadence.',
    timbreDescriptionZh: '活力满满、快节奏明快，年轻阳光，带有充沛的朝气与高频感染力。',
    bestFor: 'Tech podcasts, gaming commentary, explainer videos, and commercial promos',
    bestForZh: '数码开箱测评、电竞游戏解说、快节奏播客与美式青春感广告',
    tone: ['Playful', 'Energetic', 'Lively', 'Bright'],
    toneZh: ['青春活力', '快节奏明快', '幽默跳跃', '充满朝气'],
    pitchGuide: 'Tenor / High-Mid register',
    pitchGuideZh: '男高音 / 中高音区',
    recommendedLanguages: ['en'],
    suitabilityTagZh: '⚡ 最适英语 (美式年轻快节奏)',
    suitabilityTagEn: '⚡ Best for English (Upbeat US Cadence)',
    suitabilityDescriptionZh: '美式英语语调与弱读连读极强，非常地道活泼，讲英语极具感染力；讲中文语速偏快、风格偏潮酷。',
    suitabilityDescriptionEn: 'Native-level natural American rhythm, stress patterns, and fast-paced enthusiasm make it unmatched for English media.',
  },
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'Masculine',
    timbreDescription: 'Resonant, gravelly, and seasoned with smoky low undertones and dramatic gravity.',
    timbreDescriptionZh: '烟嗓磁性、沧桑沉淀，带有独特的沙哑颗粒感与阅尽人事的质感。',
    bestFor: 'Historical documentaries, noir fiction, mature characters, and wise mentors',
    bestForZh: '西部/黑帮悬疑小说、老电影独白、老者智慧长者角色与历史探秘',
    tone: ['Gravelly', 'Smoky', 'Seasoned', 'Grounded'],
    toneZh: ['磁性烟嗓', '沧桑厚重', '颗粒质感', '深沉内敛'],
    pitchGuide: 'Low Bass / 90-105 Hz',
    pitchGuideZh: '深沉贝斯大提琴 / 90-105 Hz',
    recommendedLanguages: ['en'],
    suitabilityTagZh: '📻 最适英语 (美/英式烟嗓故事感)',
    suitabilityTagEn: '📻 Best for English (Gritty Noir & Doc)',
    suitabilityDescriptionZh: '浓郁的英语口音颗粒与低沉声带震颤，极具西方黑胶唱片与纪录片质感；讲中文略带西式低音厚度。',
    suitabilityDescriptionEn: 'Smoky acoustic gravel and relaxed pauses create a seasoned cinematic grit particularly convincing in English.',
  },
];

export const VOICE_STYLE_PRESETS: VoiceStylePreset[] = [
  {
    id: 'natural',
    name: 'Natural Conversational',
    nameZh: '自然交谈',
    icon: 'MessageSquare',
    description: 'Relaxed, friendly, and unhurried speaking rhythm',
    descriptionZh: '轻松亲切，如好友面对面娓娓道来',
    stylePrompt: 'Relaxed, authentic conversational tone, spoken like an intelligent friend sharing thoughts at an unhurried, natural pace.',
    category: 'Casual',
  },
  {
    id: 'news-anchor',
    name: 'Broadcast Anchor',
    nameZh: '专业播音员',
    icon: 'Radio',
    description: 'Crisp, articulate, authoritative, and measured pace',
    descriptionZh: '字正腔圆，端庄严肃，标准新闻电视台播报范',
    stylePrompt: 'Crisp, professional broadcast television news anchor with pristine diction, measured cadence, and balanced neutrality.',
    category: 'Broadcast',
  },
  {
    id: 'storyteller',
    name: 'Audiobook Storyteller',
    nameZh: '有声书讲书人',
    icon: 'BookOpen',
    description: 'Warm, expressive, captivating narrative delivery',
    descriptionZh: '温润抓人，富有画面感与起承转合的情感变化',
    stylePrompt: 'Warm, captivating master storyteller with rich vocal color, subtle emotional weight, and theatrical pacing that brings prose alive.',
    category: 'Story',
  },
  {
    id: 'movie-trailer',
    name: 'Dramatic Cinematic',
    nameZh: '史诗电影旁白',
    icon: 'Film',
    description: 'Deep, resonant, intense suspense and gravitas',
    descriptionZh: '浑厚震撼，重音分明，悬念迭起的电影预告片感',
    stylePrompt: 'Deep, resonant, theatrical movie trailer voice with intense gravitas, deliberate pregnant pauses, and gripping cinematic suspense.',
    category: 'Commercial',
  },
  {
    id: 'meditation',
    name: 'Zen Mindfulness',
    nameZh: '正念禅意冥想',
    icon: 'Sparkles',
    description: 'Soft, slow, tranquil whisper-like warmth',
    descriptionZh: '放慢呼吸，温柔安抚，如微风拂面的宁静感',
    stylePrompt: 'Gentle, soothing mindfulness guide with soft breathy delivery, spacious pauses, and deeply calming, grounding tranquility.',
    category: 'Emotion',
  },
  {
    id: 'tech-reviewer',
    name: 'Hype Tech Reviewer',
    nameZh: '极客数码测评',
    icon: 'Zap',
    description: 'Brisk, punchy, enthusiastic, and forward-leaning',
    descriptionZh: '节奏明快，重点突出，充满科技激情的开箱评测',
    stylePrompt: 'High-energy, enthusiastic tech YouTuber with punchy inflection, upbeat pacing, sharp emphasis on key specs, and engaging charisma.',
    category: 'Commercial',
  },
  {
    id: 'bedtime',
    name: 'Bedtime Whisper',
    nameZh: '睡前悄悄话',
    icon: 'Moon',
    description: 'Quiet, intimate, soothing, and hushed warmth',
    descriptionZh: '轻声耳语，温软柔和，催眠助眠的静谧心绪',
    stylePrompt: 'Quiet, hushed, warm bedtime story whisper with gentle cadence, comforting softness, and serene rhythm.',
    category: 'Emotion',
  },
  {
    id: 'sarcastic',
    name: 'Wry & Sarcastic',
    nameZh: '幽默戏谑',
    icon: 'Smile',
    description: 'Dry wit, skeptical nuance, and deadpan timing',
    descriptionZh: '带着俏皮嘲讽与幽默反差的叙述风格',
    stylePrompt: 'Wry, witty, slightly sarcastic delivery with deadpan comedic timing, subtle eyebrow-raise inflections, and playful skepticism.',
    category: 'Casual',
  },
];

export const VOCAL_BURSTS = [
  { tag: '<breath>', label: '自然吸气 Breath', desc: 'Adds natural inhalation pause' },
  { tag: '<laugh>', label: '轻笑 Laugh', desc: 'Light vocal chuckle' },
  { tag: '<gasp>', label: '倒吸气 Gasp', desc: 'Sudden intake of breath' },
  { tag: '<sigh>', label: '叹气 Sigh', desc: 'Subtle exhaled release' },
  { tag: '|yeah|', label: '|yeah| 语气词', desc: 'Conversational backchannel' },
  { tag: '|mhm|', label: '|mhm| 嗯语气', desc: 'Agreement backchannel' },
  { tag: '|right|', label: '|right| 对语气', desc: 'Affirmative nuance' },
];

export const SAMPLE_SCRIPTS: SampleScript[] = [
  // Chinese Sample Scripts
  {
    id: 'zh-story',
    title: 'Night in the Pine Forest (Chinese story)',
    titleZh: '林海夜行 (中文故事)',
    category: '故事文学',
    categoryZh: '故事文学',
    language: 'zh',
    text: '薄雾笼罩着寂静的松林，月光透过繁茂的枝桠，在青苔石阶上洒下斑驳银光。<breath> 古老钟楼里的守灯人轻轻擦拭着铜镜，等待着远方归来的旅人。',
    suggestedStyleId: 'storyteller',
    suggestedVoice: 'Kore',
  },
  {
    id: 'zh-tech',
    title: 'Acoustic AI Launch (Chinese tech)',
    titleZh: '声学智能发布 (中文科技)',
    category: '前沿科技',
    categoryZh: '前沿科技',
    language: 'zh',
    text: '今天，我们正式发布新一代实时声学音色复刻引擎。<breath> 它不仅能精确解析人声共振峰，更能完整复刻说话人的细微气声与情感起伏。|yeah| 这将彻底革新声音内容的创作边界。',
    suggestedStyleId: 'tech-reviewer',
    suggestedVoice: 'Zephyr',
  },
  {
    id: 'zh-meditation',
    title: 'Breath & Mindfulness (Chinese meditation)',
    titleZh: '呼吸与正念 (中文冥想)',
    category: '健康疗愈',
    categoryZh: '健康疗愈',
    language: 'zh',
    text: '请轻轻闭上双眼，感受空气穿过鼻腔的微凉…… <breath> 慢慢吸气，停留三秒…… <sigh> 然后温柔地吐出来。让紧绷的肩膀慢慢沉下来，感受当下的宁静。',
    suggestedStyleId: 'meditation',
    suggestedVoice: 'Kore',
  },
  {
    id: 'zh-cinema',
    title: 'Edge of the Stars (Chinese epic)',
    titleZh: '星际边缘 (中文史诗)',
    category: '史诗电影',
    categoryZh: '史诗电影',
    language: 'zh',
    text: '当最后一道恒星的光芒在视界边缘隐没，人类舰队只剩下了唯一的坐标。<breath> 在无尽深空之中，有些信念永不熄灭。',
    suggestedStyleId: 'movie-trailer',
    suggestedVoice: 'Fenrir',
  },

  // English Sample Scripts
  {
    id: 'en-storybook',
    title: 'Fantasy Narrative (English)',
    titleZh: '奇幻叙事 (英文)',
    category: 'Storytelling',
    categoryZh: '英文文学',
    language: 'en',
    text: 'Beyond the velvet mist of the Whispering Woods, an ancient lantern flickered atop the observatory tower. <breath> It had not been lit in three hundred years.',
    suggestedStyleId: 'storyteller',
    suggestedVoice: 'Kore',
  },
  {
    id: 'en-tech',
    title: 'Keynote Reveal (English)',
    titleZh: '科技发布会 (英文)',
    category: 'Tech Keynote',
    categoryZh: '英文科技',
    language: 'en',
    text: "Today, we are thrilled to reveal a breakthrough in acoustic neural modeling. <breath> It doesn't merely read text—it captures the soul, cadence, and breath of human expression.",
    suggestedStyleId: 'tech-reviewer',
    suggestedVoice: 'Puck',
  },
  {
    id: 'en-cinema',
    title: 'Movie Trailer (English)',
    titleZh: '好莱坞预告 (英文)',
    category: 'Cinematic',
    categoryZh: '英文电影',
    language: 'en',
    text: 'In a world where memories can be rewritten before dawn, one operative will risk everything to remember what really happened. <breath> Some secrets refuse to be erased.',
    suggestedStyleId: 'movie-trailer',
    suggestedVoice: 'Fenrir',
  },
  {
    id: 'en-dialogue',
    title: 'Casual Chat (English)',
    titleZh: '日常播客 (英文)',
    category: 'Podcast',
    categoryZh: '英文播客',
    language: 'en',
    text: 'Honestly? <laugh> I never expected the sound synthesis to hit this level of detail on the first pass. |yeah| The subtle timbre harmonics are remarkably lifelike.',
    suggestedStyleId: 'natural',
    suggestedVoice: 'Charon',
  },
];
